### PR TITLE
Add Model Identifer to search results

### PR DESCRIPTION
**Pull request by mrkalmdn**
Hi, @pascalbaljet!

This PR is related to issues #5 and #41. I have added an `includeModelIdentifer` method to add an identifier to the search results.

### CODE REVIEW

**Comment by assoft** [comment]
Thank you @mrkalmdn 

Absolutely i need this... 

Right now I'm getting this by manipulating the data. 

Surely it would be cool to have something like this internally. Hopefully it will be merged soon.

**Comment by mrkalmdn** [comment]
Thank you, @assoft! 🍻

**Comment by pascalbaljet** [comment]
Thhanks @mrkalmdn! This is now available in v2.6.0, but I renamed the method to `includeModelType`, and you can customize the key :)

**Comment by mrkalmdn** [comment]
Thank you, @pascalbaljet! 🍻

**Pull request merged**
